// quivr-plugin-api generates SDK and reference version declarations from the
// engine's Plugin API feature table. It is a repository maintenance tool.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"

	"github.com/The-Vibe-Company/quivr-v2/internal/plugins"
)

const begin = "<!-- plugin-api: generated by make generate -->"
const end = "<!-- /plugin-api -->"

func main() {
	check := flag.Bool("check", false, "fail if generated outputs are stale")
	flag.Parse()
	if err := generate(*check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(check bool) error {
	versions := plugins.SupportedPluginAPIVersions
	quoted := make([]string, len(versions))
	for i, v := range versions {
		quoted[i] = strconv.Quote(v)
	}
	var goCode, pyCode strings.Builder
	fmt.Fprintf(&goCode, "// Code generated by make generate; DO NOT EDIT.\npackage quivrplugin\n\n// PluginAPIVersion is the newest Plugin API version this SDK implements.\nconst PluginAPIVersion = %q\n\n// SupportedPluginAPIVersions are served oldest first; discovery negotiates the highest admitted version.\nvar SupportedPluginAPIVersions = []string{%s}\n\n// FeatureSince records the Plugin API version that introduced each feature.\nvar FeatureSince = map[string]string{\n", plugins.PluginAPIVersion, strings.Join(quoted, ", "))
	fmt.Fprintf(&pyCode, "# Code generated by make generate; DO NOT EDIT.\n\nPLUGIN_API_VERSION = %q\nSUPPORTED_PLUGIN_API_VERSIONS = (%s,)\nFEATURE_SINCE = {\n", plugins.PluginAPIVersion, strings.Join(quoted, ", "))
	var history strings.Builder
	fmt.Fprintf(&history, "Latest Plugin API: `%s`. Supported versions: `%s`.\n\n| Feature | Since |\n| --- | --- |\n", plugins.PluginAPIVersion, strings.Join(versions, "`, `"))
	for _, row := range plugins.FeatureTable() {
		fmt.Fprintf(&goCode, "%q: %q,\n", row.Feature, row.Since)
		fmt.Fprintf(&pyCode, "    %q: %q,\n", row.Feature, row.Since)
		fmt.Fprintf(&history, "| %s | `%s` |\n", row.Description, row.Since)
	}
	goCode.WriteString(`}

// apiFeatures resolves admission once per loaded plugin manifest.
type apiFeatures map[string]bool

func (features apiFeatures) speaks(feature string) bool { return features[feature] }

func resolveAPIFeatures(version string) apiFeatures {
    features := make(apiFeatures, len(FeatureSince))
    for feature, since := range FeatureSince {
        features[feature] = compareVersions(version, since) >= 0
    }
    return features
}
`)
	pyCode.WriteString("}\n")
	formatted, err := format.Source([]byte(goCode.String()))
	if err != nil {
		return err
	}
	outputs := map[string][]byte{
		"sdks/go/quivrplugin/api.gen.go":               formatted,
		"sdks/python/src/quivr_plugin/api_versions.py": []byte(pyCode.String()),
	}
	for _, path := range []string{"contracts/plugins/v0/README.md", "sdks/go/README.md", "sdks/python/README.md"} {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		text := string(data)
		a, b := strings.Index(text, begin), strings.Index(text, end)
		if a < 0 || b < a {
			return fmt.Errorf("%s: missing Plugin API generation markers", path)
		}
		section := history.String()
		if path != "contracts/plugins/v0/README.md" {
			section = fmt.Sprintf("Discovery serves the highest version the manifest admits, through Plugin API `%s`.\nSee the [feature history](../../contracts/plugins/v0/README.md#plugin-api-versions).\n", plugins.PluginAPIVersion)
		}
		outputs[path] = []byte(text[:a+len(begin)] + "\n" + section + text[b:])
	}
	// Sorted paths keep stale-output diagnostics deterministic.
	paths := []string{"contracts/plugins/v0/README.md", "sdks/go/README.md", "sdks/go/quivrplugin/api.gen.go", "sdks/python/README.md", "sdks/python/src/quivr_plugin/api_versions.py"}
	var stale []string
	for _, path := range paths {
		want := outputs[path]
		have, err := os.ReadFile(path)
		if err != nil && !os.IsNotExist(err) {
			return err
		}
		if bytes.Equal(have, want) {
			continue
		}
		if check {
			stale = append(stale, path)
			continue
		}
		if err := os.WriteFile(path, want, 0644); err != nil {
			return err
		}
	}
	if len(stale) > 0 {
		return fmt.Errorf("Plugin API declarations are stale; run make generate: %s", strings.Join(stale, ", "))
	}
	return nil
}
