// Code generated by make generate; DO NOT EDIT.
package quivrplugin

// PluginAPIVersion is the newest Plugin API version this SDK implements.
const PluginAPIVersion = "0.16.0"

// SupportedPluginAPIVersions are served oldest first; discovery negotiates the highest admitted version.
var SupportedPluginAPIVersions = []string{"0.1.0", "0.2.0", "0.3.0", "0.3.1", "0.4.0", "0.5.0", "0.6.0", "0.7.0", "0.8.0", "0.9.0", "0.10.0", "0.11.0", "0.12.0", "0.13.0", "0.14.0", "0.15.0", "0.16.0"}

// FeatureSince records the Plugin API version that introduced each feature.
var FeatureSince = map[string]string{
	"normalizer":                       "0.1.0",
	"subscription":                     "0.2.0",
	"connector":                        "0.3.0",
	"instance_scope":                   "0.3.1",
	"attachments":                      "0.4.0",
	"push":                             "0.5.0",
	"ingestion":                        "0.6.0",
	"retrieval":                        "0.7.0",
	"segments_only":                    "0.8.0",
	"input_price":                      "0.9.0",
	"subscription_vectors":             "0.10.0",
	"connector_api":                    "0.11.0",
	"connector_signature":              "0.12.0",
	"instance_token":                   "0.12.0",
	"profile_candidates":               "0.12.0",
	"profile_candidate_mode":           "0.13.0",
	"signed_calls":                     "0.14.0",
	"connector_submission_concurrency": "0.15.0",
	"connector_attachment_only":        "0.15.0",
	"coverage_snapshots":               "0.16.0",
}

// apiFeatures resolves admission once per loaded plugin manifest.
type apiFeatures map[string]bool

func (features apiFeatures) speaks(feature string) bool { return features[feature] }

func resolveAPIFeatures(version string) apiFeatures {
	features := make(apiFeatures, len(FeatureSince))
	for feature, since := range FeatureSince {
		features[feature] = compareVersions(version, since) >= 0
	}
	return features
}
