# Code generated by make generate; DO NOT EDIT.

PLUGIN_API_VERSION = "0.11.0"
SUPPORTED_PLUGIN_API_VERSIONS = ("0.1.0", "0.2.0", "0.3.0", "0.3.1", "0.4.0", "0.5.0", "0.6.0", "0.7.0", "0.8.0", "0.9.0", "0.10.0", "0.11.0",)
FEATURE_SINCE = {
    "normalizer": "0.1.0",
    "subscription": "0.2.0",
    "connector": "0.3.0",
    "instance_scope": "0.3.1",
    "attachments": "0.4.0",
    "push": "0.5.0",
    "ingestion": "0.6.0",
    "retrieval": "0.7.0",
    "segments_only": "0.8.0",
    "input_price": "0.9.0",
    "subscription_vectors": "0.10.0",
    "connector_api": "0.11.0",
}
