"""Typed Plugin Protocol v0 models.

Code generated by sdks/python/scripts/generate.py from contracts/shared/v0 and
contracts/plugins/v0. DO NOT EDIT.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from ._codec import Model


@dataclass(kw_only=True)
class SourceIdentity(Model):
    corpus_id: str
    namespace: str
    record_key: str


@dataclass(kw_only=True)
class ExtensionEntry(Model):
    schema_version: str
    data: dict[str, Any]


@dataclass(kw_only=True)
class TextContent(Model):
    kind: Literal["text"] = "text"
    text: str


@dataclass(kw_only=True)
class BlobContent(Model):
    kind: Literal["blob"] = "blob"
    blob_id: str
    media_type: str


@dataclass(kw_only=True)
class Part(Model):
    key: str
    parent_key: str | None = None
    role: str
    content: TextContent | BlobContent
    extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class RelationInput(Model):
    "Source-provided link to an independently identified Record in the same Organization. Optional source revision preserves provenance; ordinary expansion resolves the current eligible target. Missing targets do not block readiness. Every expansion reauthorizes the target. Precise Part-target syntax remains outside this initial draft."

    type: str
    target: SourceIdentity
    source_target_revision: str | None = None


@dataclass(kw_only=True)
class ManifestContent(Model):
    "Unique Part keys, acyclic parent references within this Manifest, and verified same-Organization Blobs are checked before atomic publication. These semantic constraints need server validation in addition to JSON Schema."

    kind: Literal["manifest"] = "manifest"
    parts: list[Part]
    relations: list[RelationInput] | None = None


@dataclass(kw_only=True)
class Provenance(Model):
    source_blob_ids: list[str] | None = None
    producer: str | None = None
    producer_version: str | None = None


@dataclass(kw_only=True)
class SignedUrlReference(Model):
    "Short-lived signed GET URL for the input Blob."

    kind: Literal["signed_url"] = "signed_url"
    url: str
    expires_at: str


@dataclass(kw_only=True)
class FileReference(Model):
    "Local development only: a file URL readable by the plugin."

    kind: Literal["file"] = "file"
    url: str


@dataclass(kw_only=True)
class InputBlob(Model):
    blob_id: str
    media_type: str
    size_bytes: int
    sha256: str
    reference: SignedUrlReference | FileReference


@dataclass(kw_only=True)
class NormalizerRequest(Model):
    "POST /v0/contributions/normalizer. Immutable invocation context plus a reference to the input Blob; bodies are never inline."

    invocation_id: str
    idempotency_key: str
    contribution: Literal["normalizer"] = "normalizer"
    organization_id: str
    corpus_id: str
    record_id: str
    record_version_id: str
    source: SourceIdentity
    input: InputBlob
    extensions: dict[str, ExtensionEntry] | None = None
    provenance: Provenance | None = None
    configuration: dict[str, Any]


@dataclass(kw_only=True)
class ResponseWarning(Model):
    code: str
    message: str


@dataclass(kw_only=True)
class NormalizerResponse(Model):
    "200 body of POST /v0/contributions/normalizer. The Manifest uses the exact public Manifest shape; the engine applies the same semantic validation as for kind manifest submissions before anything is committed."

    manifest: ManifestContent
    extensions: dict[str, ExtensionEntry] | None = None
    language: str | None = None
    warnings: list[ResponseWarning] | None = None


@dataclass(kw_only=True)
class PluginIdentity(Model):
    id: str
    version: str


@dataclass(kw_only=True)
class Discovery(Model):
    "GET /v0/discovery. manifest_digest is sha256 over the exact bytes of the quivr-plugin.yaml the plugin was built from; the engine compares it with the pinned manifest."

    plugin_api: str
    plugin: PluginIdentity
    manifest_digest: str
    contributions: list[Literal["normalizer"]]


@dataclass(kw_only=True)
class Health(Model):
    "GET /v0/health returns 200 with this body when the plugin can accept invocations; otherwise 503 with the error envelope."

    status: Literal["ok"] = "ok"


@dataclass(kw_only=True)
class ErrorEnvelope(Model):
    "Body of every non-2xx plugin response. retryable is authoritative: true asks the engine to retry within the declared retry intent; false is terminal."

    code: str
    message: str
    retryable: bool


@dataclass(kw_only=True)
class ManifestCompatibility(Model):
    engine: str
    plugin_api: str


@dataclass(kw_only=True)
class RetryIntent(Model):
    "Retry intent for plugin-declared retryable errors; the engine may cap it."

    max_attempts: int


@dataclass(kw_only=True)
class OutputLimits(Model):
    max_response_bytes: int | None = None
    max_parts: int | None = None


@dataclass(kw_only=True)
class NormalizerContribution(Model):
    media_types: list[str]
    timeout_ms: int | None = None
    retry: RetryIntent | None = None
    limits: OutputLimits | None = None


@dataclass(kw_only=True)
class ManifestContributions(Model):
    "Keyed by Contribution name. Plugin API 0.1 accepts only normalizer; the other names are reserved and rejected."

    normalizer: NormalizerContribution


@dataclass(kw_only=True)
class ManifestConfiguration(Model):
    schema: Any


@dataclass(kw_only=True)
class Secret(Model):
    name: str
    description: str | None = None
    required: bool | None = None


@dataclass(kw_only=True)
class RunCommand(Model):
    "Language-neutral local development command (argv, no shell)."

    command: list[str]


@dataclass(kw_only=True)
class PluginManifest(Model):
    "Declares one plugin: identity, compatibility ranges, Contributions, configuration schema, required secrets, owned extension namespaces and a local run command. Written as YAML; validated as the equivalent JSON value. Semantic rules this schema cannot express (satisfiable ranges, compatibility, namespace prefix, schemas that compile) are listed in README.md."

    id: str
    version: str
    description: str | None = None
    compatibility: ManifestCompatibility
    contributions: ManifestContributions
    configuration: ManifestConfiguration | None = None
    secrets: list[Secret] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    run: RunCommand | None = None


@dataclass(kw_only=True)
class FixtureInput(Model):
    path: str
    media_type: str


@dataclass(kw_only=True)
class InvocationFixture(Model):
    "A language-neutral local test input for a normalizer. Tools (quivr plugin dev, the Contract Runner, SDK test helpers) turn it into a normalizer request: they read input.path relative to the fixture file, compute its size and SHA-256, reference it through an absolute file:// URL, and fill the identity fields with deterministic development values."

    description: str | None = None
    input: FixtureInput
    configuration: dict[str, Any] | None = None
    source: SourceIdentity | None = None
    extensions: dict[str, ExtensionEntry] | None = None
    provenance: Provenance | None = None


# Keys are extension namespaces.
Extensions = dict[str, ExtensionEntry]

__all__ = [
    "BlobContent",
    "Discovery",
    "ErrorEnvelope",
    "ExtensionEntry",
    "Extensions",
    "FileReference",
    "FixtureInput",
    "Health",
    "InputBlob",
    "InvocationFixture",
    "ManifestCompatibility",
    "ManifestConfiguration",
    "ManifestContent",
    "ManifestContributions",
    "NormalizerContribution",
    "NormalizerRequest",
    "NormalizerResponse",
    "OutputLimits",
    "Part",
    "PluginIdentity",
    "PluginManifest",
    "Provenance",
    "RelationInput",
    "ResponseWarning",
    "RetryIntent",
    "RunCommand",
    "Secret",
    "SignedUrlReference",
    "SourceIdentity",
    "TextContent",
]
