"""Typed Plugin Protocol v0 models.

Code generated by sdks/python/scripts/generate.py from contracts/shared/v0 and
contracts/plugins/v0. DO NOT EDIT.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from ._codec import Model


@dataclass(kw_only=True)
class SourceIdentity(Model):
    corpus_id: str
    namespace: str
    record_key: str


@dataclass(kw_only=True)
class ExtensionEntry(Model):
    schema_version: str
    data: dict[str, Any]


@dataclass(kw_only=True)
class TextContent(Model):
    kind: Literal["text"] = "text"
    text: str


@dataclass(kw_only=True)
class BlobContent(Model):
    kind: Literal["blob"] = "blob"
    blob_id: str
    media_type: str


@dataclass(kw_only=True)
class Part(Model):
    key: str
    parent_key: str | None = None
    role: str
    content: TextContent | BlobContent
    extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class RelationInput(Model):
    "Source-provided link to an independently identified Record in the same Organization. Optional source revision preserves provenance; ordinary expansion resolves the current eligible target. Missing targets do not block readiness. Every expansion reauthorizes the target. Precise Part-target syntax remains outside this initial draft."

    type: str
    target: SourceIdentity
    source_target_revision: str | None = None


@dataclass(kw_only=True)
class ManifestContent(Model):
    "Unique Part keys, acyclic parent references within this Manifest, and verified same-Organization Blobs are checked before atomic publication. These semantic constraints need server validation in addition to JSON Schema."

    kind: Literal["manifest"] = "manifest"
    parts: list[Part]
    relations: list[RelationInput] | None = None


@dataclass(kw_only=True)
class NormalizationProvenanceFallback(Model):
    "Present when the route is optional and the normalizer failed: the published Manifest comes from the built-in text path, and invocation_id names the failed invocation."

    code: str
    message: str


@dataclass(kw_only=True)
class NormalizationProvenance(Model):
    "Engine-owned record of the external normalizer invocation whose output a Record Version publishes. Present only on read; a submission that sets it is rejected. producer and producer_version keep naming the acquirer, and source_blob_ids keeps the input Blob."

    plugin_id: str
    plugin_version: str
    plugin_api: str
    contribution: Literal["normalizer"] = "normalizer"
    invocation_id: str
    idempotency_key: str
    input_sha256: str
    fallback: NormalizationProvenanceFallback | None = None


@dataclass(kw_only=True)
class Provenance(Model):
    source_blob_ids: list[str] | None = None
    producer: str | None = None
    producer_version: str | None = None
    normalization: NormalizationProvenance | None = None


@dataclass(kw_only=True)
class SignedUrlReference(Model):
    "Short-lived signed GET URL for the input Blob."

    kind: Literal["signed_url"] = "signed_url"
    url: str
    expires_at: str


@dataclass(kw_only=True)
class FileReference(Model):
    "Local development only: a file URL readable by the plugin."

    kind: Literal["file"] = "file"
    url: str


@dataclass(kw_only=True)
class InputBlob(Model):
    blob_id: str
    media_type: str
    size_bytes: int
    sha256: str
    reference: SignedUrlReference | FileReference


@dataclass(kw_only=True)
class NormalizerRequest(Model):
    "POST /v0/contributions/normalizer. Immutable invocation context plus a reference to the input Blob; bodies are never inline."

    invocation_id: str
    idempotency_key: str
    contribution: Literal["normalizer"] = "normalizer"
    organization_id: str
    corpus_id: str
    record_id: str
    record_version_id: str
    source: SourceIdentity
    input: InputBlob
    extensions: dict[str, ExtensionEntry] | None = None
    provenance: Provenance | None = None
    configuration: dict[str, Any]


@dataclass(kw_only=True)
class ResponseWarning(Model):
    code: str
    message: str


@dataclass(kw_only=True)
class NormalizerResponse(Model):
    "200 body of POST /v0/contributions/normalizer. The Manifest uses the exact public Manifest shape; the engine applies the same semantic validation as for kind manifest submissions before anything is committed."

    manifest: ManifestContent
    extensions: dict[str, ExtensionEntry] | None = None
    language: str | None = None
    warnings: list[ResponseWarning] | None = None


@dataclass(kw_only=True)
class PluginIdentity(Model):
    id: str
    version: str


@dataclass(kw_only=True)
class Discovery(Model):
    "GET /v0/discovery. manifest_digest is sha256 over the exact bytes of the quivr-plugin.yaml the plugin was built from; the engine compares it with the pinned manifest."

    plugin_api: str
    plugin: PluginIdentity
    manifest_digest: str
    contributions: list[Literal["normalizer", "subscription", "connector", "ingestion", "retrieval"]]


@dataclass(kw_only=True)
class Health(Model):
    "GET /v0/health returns 200 with this body when the plugin can accept invocations; otherwise 503 with the error envelope."

    status: Literal["ok"] = "ok"


@dataclass(kw_only=True)
class ErrorEnvelope(Model):
    "Body of every non-2xx plugin response. retryable is authoritative: true asks the engine to retry within the declared retry intent; false is terminal. Connector errors (since Plugin API 0.3) also carry error_class, and optionally retry_after_seconds."

    code: str
    message: str
    retryable: bool
    error_class: Literal["access", "transient", "source"] | None = None
    retry_after_seconds: int | None = None


@dataclass(kw_only=True)
class ManifestCompatibility(Model):
    engine: str
    plugin_api: str


@dataclass(kw_only=True)
class RetryIntent(Model):
    "Retry intent for plugin-declared retryable errors; the engine may cap it."

    max_attempts: int


@dataclass(kw_only=True)
class OutputLimits(Model):
    max_response_bytes: int | None = None
    max_parts: int | None = None


@dataclass(kw_only=True)
class NormalizerContribution(Model):
    media_types: list[str]
    timeout_ms: int | None = None
    retry: RetryIntent | None = None
    limits: OutputLimits | None = None


@dataclass(kw_only=True)
class SubscriptionLimits(Model):
    max_response_bytes: int | None = None


@dataclass(kw_only=True)
class SubscriptionContributionVectors(Model):
    "Since Plugin API 0.10. Opt in to canonical Part vectors and saved query vectors. query_text_pointer selects a string in the expression by RFC 6901 JSON Pointer; the core embeds it when the Saved Query Version is created."

    parts: bool | None = None
    query: bool | None = None
    query_text_pointer: str | None = None
    query_expression_schema: Any | None = None


@dataclass(kw_only=True)
class SubscriptionContribution(Model):
    "An alert rule, since Plugin API 0.2: decides whether one Record Version matches each Saved Query expression of a batch."

    expression_schema: Any
    configuration_schema: Any | None = None
    max_batch_size: int | None = None
    timeout_ms: int | None = None
    retry: RetryIntent | None = None
    limits: SubscriptionLimits | None = None
    vectors: SubscriptionContributionVectors | None = None


@dataclass(kw_only=True)
class ConnectorAPIRoute(Model):
    name: str
    method: Literal["GET", "POST"]
    path: str
    auth: Literal["quivr_key"] = "quivr_key"
    request_schema: Any | None = None


@dataclass(kw_only=True)
class ConnectorAPI(Model):
    "Since Plugin API 0.11: routes secured by a Quivr key with connector:push on the instance Corpus. Requires push mode."

    routes: list[ConnectorAPIRoute]


@dataclass(kw_only=True)
class ConnectorKind(Model):
    description: str | None = None
    config_schema: Any
    credential_schema: Any | None = None
    credential_required: bool | None = None
    default_interval_seconds: int
    modes: list[Literal["pull", "push"]] | None = None
    api: ConnectorAPI | None = None


@dataclass(kw_only=True)
class ConnectorLimits(Model):
    max_response_bytes: int | None = None
    max_items: int | None = None
    max_checkpoint_bytes: int | None = None


@dataclass(kw_only=True)
class ConnectorContributionAttachments(Model):
    "Since Plugin API 0.4: items may carry attachments. The core asks for each attachment's size and SHA-256 (describe_attachment), issues an upload grant and has the plugin upload the bytes against it (upload_attachment). Without this block a page with attachments is refused."

    max_bytes: int | None = None
    timeout_ms: int | None = None


@dataclass(kw_only=True)
class ConnectorContribution(Model):
    "Source collectors, since Plugin API 0.3: fetch pages of new or changed items from a source after an opaque checkpoint. The core keeps Connector Instances, schedules, checkpoints, credentials and health."

    kinds: dict[str, ConnectorKind]
    timeout_ms: int | None = None
    limits: ConnectorLimits | None = None
    attachments: ConnectorContributionAttachments | None = None


@dataclass(kw_only=True)
class VectorSpaceInputPrice(Model):
    "Since Plugin API 0.9: what embedding text in this space costs, for the estimate a backfill shows before it starts. Absent, the cost of a backfill is unknown."

    usd_per_million_tokens: float


@dataclass(kw_only=True)
class VectorSpace(Model):
    "One vector space the plugin owns. Its identity is the id and the version together: vectors of another version belong to another space."

    version: str
    model: str
    dimensions: int
    metric: Literal["cosine", "dot", "l2"]
    indexes: list[Literal["text"]]
    query_modalities: list[Literal["text"]]
    description: str | None = None
    input_price: VectorSpaceInputPrice | None = None


@dataclass(kw_only=True)
class IngestionLimits(Model):
    max_segments: int | None = None
    max_response_bytes: int | None = None


@dataclass(kw_only=True)
class Ingestion(Model):
    "Segmentation and embedding, since Plugin API 0.6: cut one Record Version's text Parts into segments and embed each segment in the vector spaces the plugin owns (segment_and_embed), and encode a query into one of those spaces (embed_query). The core keeps the index, the registry of spaces, authorization, withdrawal and projection generations."

    spaces: dict[str, VectorSpace]
    timeout_ms: int | None = None
    query_timeout_ms: int | None = None
    limits: IngestionLimits | None = None


@dataclass(kw_only=True)
class RetrievalProfile(Model):
    "One search profile and its budgets."

    description: str | None = None
    max_latency_ms: int
    max_cost_cents: float


@dataclass(kw_only=True)
class RetrievalLimits(Model):
    max_rounds: int | None = None
    max_requests: int | None = None
    max_candidates: int | None = None
    max_response_bytes: int | None = None


@dataclass(kw_only=True)
class Retrieval(Model):
    "Search, since Plugin API 0.7: answer one search in rounds. Each round the plugin either asks the core for candidates (keyword, vector on a named space, hybrid) or returns the final ranking, chosen only among candidates the core served in this search. The core keeps the index, encodes queries with each space's owner, and applies authorization, withdrawal and generation routing before serving any candidate."

    profiles: dict[str, RetrievalProfile]
    limits: RetrievalLimits | None = None


@dataclass(kw_only=True)
class ManifestContributions(Model):
    "Keyed by Contribution name. A manifest declares at least one of normalizer (since Plugin API 0.1), subscription (since 0.2), connector (since 0.3), ingestion (since 0.6) and retrieval (since 0.7). The other names are reserved and rejected."

    normalizer: NormalizerContribution | None = None
    subscription: SubscriptionContribution | None = None
    connector: ConnectorContribution | None = None
    ingestion: Ingestion | None = None
    retrieval: Retrieval | None = None


@dataclass(kw_only=True)
class ManifestConfiguration(Model):
    schema: Any


@dataclass(kw_only=True)
class Secret(Model):
    name: str
    description: str | None = None
    required: bool | None = None


@dataclass(kw_only=True)
class RunCommand(Model):
    "Language-neutral local development command (argv, no shell)."

    command: list[str]


@dataclass(kw_only=True)
class PluginManifest(Model):
    "Declares one plugin: identity, compatibility ranges, Contributions, configuration schema, required secrets, owned extension namespaces and a local run command. Written as YAML; validated as the equivalent JSON value. Semantic rules this schema cannot express (satisfiable ranges, compatibility, namespace prefix, schemas that compile) are listed in README.md."

    id: str
    version: str
    description: str | None = None
    compatibility: ManifestCompatibility
    contributions: ManifestContributions
    configuration: ManifestConfiguration | None = None
    secrets: list[Secret] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    run: RunCommand | None = None


@dataclass(kw_only=True)
class FixtureInput(Model):
    path: str
    media_type: str


@dataclass(kw_only=True)
class InvocationFixture(Model):
    "A language-neutral local test input for a normalizer. Tools (quivr plugin dev, the Contract Runner, SDK test helpers) turn it into a normalizer request: they read input.path relative to the fixture file, compute its size and SHA-256, reference it through an absolute file:// URL, and fill the identity fields with deterministic development values."

    description: str | None = None
    input: FixtureInput
    configuration: dict[str, Any] | None = None
    source: SourceIdentity | None = None
    extensions: dict[str, ExtensionEntry] | None = None
    provenance: Provenance | None = None


@dataclass(kw_only=True)
class RecordPartVectorsItem(Model):
    segment_id: str
    vector: list[float]


@dataclass(kw_only=True)
class RecordPart(Model):
    key: str
    role: str
    text: str
    vectors: list[RecordPartVectorsItem] | None = None


@dataclass(kw_only=True)
class RecordSource(Model):
    "Where the Record comes from: its Source Namespace and Record Key, and the Source Position of the accepted revision when the producer sent one. Always sent by the core since Plugin API 0.2."

    namespace: str
    record_key: str
    position: str | None = None


@dataclass(kw_only=True)
class ConnectorOrigin(Model):
    "Present when origin is connector."

    instance_id: str
    kind: str


@dataclass(kw_only=True)
class NormalizationOrigin(Model):
    "Present when an external normalizer produced the published Manifest."

    plugin_id: str
    plugin_version: str
    contribution: Literal["normalizer"] = "normalizer"
    fallback: bool | None = None


@dataclass(kw_only=True)
class RecordProvenance(Model):
    "Who produced the Version. Always sent by the core since Plugin API 0.2."

    origin: Literal["client", "connector"]
    producer: str | None = None
    producer_version: str | None = None
    connector: ConnectorOrigin | None = None
    normalization: NormalizationOrigin | None = None


@dataclass(kw_only=True)
class EvaluatedRecord(Model):
    "The evaluated Record Version."

    corpus_id: str
    record_id: str
    record_version_id: str
    enriched: bool
    parts: list[RecordPart]
    source: RecordSource | None = None
    accepted_at: str | None = None
    provenance: RecordProvenance | None = None
    extensions: dict[str, ExtensionEntry] | None = None
    vector_space_id: str | None = None
    vectors_ready: bool | None = None


@dataclass(kw_only=True)
class SubscriptionRef(Model):
    subscription_id: str
    subscription_version_id: str
    saved_query_id: str
    saved_query_version_id: str
    owner: str | None = None


@dataclass(kw_only=True)
class EvaluationQueryVector(Model):
    "Since Plugin API 0.10. Immutable vector from the semantic-search query encoder. Missing if this Saved Query Version has no vector in the article space."

    vector_space_id: str
    vector: list[float]


@dataclass(kw_only=True)
class Evaluation(Model):
    id: str
    expression: dict[str, Any]
    configuration: dict[str, Any]
    subscriptions: list[SubscriptionRef]
    query_vector: EvaluationQueryVector | None = None


@dataclass(kw_only=True)
class SubscriptionRequest(Model):
    "POST /v0/contributions/subscription, since Plugin API 0.2. One Record Version's text Parts and metadata (source identity, acceptance time, provenance, extensions) and a batch of distinct evaluations to decide. The core deduplicates Subscriptions that share the same expression and configuration into one evaluation and never sends more evaluations than the manifest's max_batch_size."

    invocation_id: str
    idempotency_key: str
    contribution: Literal["subscription"] = "subscription"
    organization_id: str
    record: EvaluatedRecord
    evaluations: list[Evaluation]
    configuration: dict[str, Any]


@dataclass(kw_only=True)
class Evidence(Model):
    "Required for match, optional otherwise."

    explanation: str
    part_keys: list[str] | None = None
    details: dict[str, Any] | None = None


@dataclass(kw_only=True)
class Decision(Model):
    id: str
    decision: Literal["match", "no_match", "not_ready"]
    evidence: Evidence | None = None


@dataclass(kw_only=True)
class SubscriptionResponse(Model):
    "200 body of POST /v0/contributions/subscription, since Plugin API 0.2. Exactly one decision per requested evaluation id. A match carries evidence; the core stores it with the Match. Bounds this schema cannot express (one decision per id, Part keys that exist in the request, details of at most 16 KiB) are listed in README.md."

    decisions: list[Decision]


@dataclass(kw_only=True)
class FixtureRecord(Model):
    enriched: bool | None = None
    parts: list[RecordPart]
    source: RecordSource | None = None
    accepted_at: str | None = None
    provenance: RecordProvenance | None = None
    extensions: dict[str, ExtensionEntry] | None = None
    vector_space_id: str | None = None
    vectors_ready: bool | None = None


@dataclass(kw_only=True)
class FixtureEvaluation(Model):
    description: str | None = None
    expression: dict[str, Any]
    configuration: dict[str, Any] | None = None
    expect: Literal["match", "no_match", "not_ready"] | None = None
    query_vector: EvaluationQueryVector | None = None


@dataclass(kw_only=True)
class SubscriptionFixture(Model):
    "A language-neutral local test input for a subscription Contribution, since Plugin API 0.2. Tools (quivr plugin dev, the Contract Runner, SDK test helpers) turn it into a subscription request: they number the evaluations e1, e2, ... in order, give each one development Subscription ids, derive the Record Version ids and the idempotency key from the SHA-256 of the fixture bytes, default the record metadata (source dev-namespace/dev-record-<digest>, origin client, accepted_at 2026-01-01T00:00:00Z) when the fixture omits it, and validate every expression and configuration against the manifest schemas. A fixture file is told apart from an invocation fixture by its top-level evaluations property."

    description: str | None = None
    configuration: dict[str, Any] | None = None
    record: FixtureRecord
    evaluations: list[FixtureEvaluation]


@dataclass(kw_only=True)
class ConnectorInstanceRef(Model):
    "The Connector Instance the core invokes the plugin for."

    instance_id: str
    kind: str
    corpus_id: str | None = None
    source_namespace: str | None = None
    webhook_url: str | None = None
    config: dict[str, Any]


@dataclass(kw_only=True)
class ConnectorFetchRequest(Model):
    "POST /v0/contributions/connector/fetch, since Plugin API 0.3. Fetch one page of new or changed source items after the checkpoint. The plugin is stateless between invocations: the core persists the checkpoint and advances it only after the page's items are durably accepted."

    invocation_id: str
    contribution: Literal["connector"] = "connector"
    organization_id: str
    configuration: dict[str, Any]
    connector: ConnectorInstanceRef
    credential: Any
    checkpoint: Any
    now: str
    page_in_run: int
    reads_today: int


@dataclass(kw_only=True)
class ConnectorAttachment(Model):
    "A binary Part of the item. Since Plugin API 0.4, the core asks for the bytes later through describe_attachment and upload_attachment, only when the item is not already accepted; the manifest must declare contributions.connector.attachments."

    key: str
    parent_key: str | None = None
    role: str
    media_type: str
    size_bytes: int | None = None
    sha256: str | None = None
    extensions: dict[str, ExtensionEntry] | None = None
    ref: str


@dataclass(kw_only=True)
class ConnectorItem(Model):
    "One source item that is new or changed since the checkpoint: the same ingestion command a client submits, with producer = the Connector Instance. Exactly one of content and withdraw: true."

    record_key: str
    revision: str | None = None
    source_position: str | None = None
    content: TextContent | ManifestContent | None = None
    extensions: dict[str, ExtensionEntry] | None = None
    withdraw: bool | None = None
    attachments: list[ConnectorAttachment] | None = None


@dataclass(kw_only=True)
class PushStatus(Model):
    "Since Plugin API 0.5, for a push kind: the plugin's view of the push channel it sets up at the source (a registered webhook and its subscriptions). active: deliveries are expected. pending: not set up yet; code may say why. failed: the source refused or broke the setup, and polling carries the collection alone; error_class access shows as the access_error Connector Health state. The core keeps the latest report."

    state: Literal["active", "pending", "failed"]
    error_class: Literal["access", "transient", "source"] | None = None
    code: str | None = None
    poll_interval_seconds: int | None = None


@dataclass(kw_only=True)
class ConnectorFetchResponse(Model):
    "200 body of POST /v0/contributions/connector/fetch. The engine validates every item as it validates a client submission before accepting it, and advances the checkpoint only after the items are durably accepted."

    items: list[ConnectorItem]
    checkpoint: Any
    more: bool
    reads: int | None = None
    diagnostics: dict[str, Any] | None = None
    notice: str | None = None
    not_due: bool | None = None
    push: PushStatus | None = None


@dataclass(kw_only=True)
class ConnectorCredentialRequest(Model):
    "POST /v0/contributions/connector/check_credential, since Plugin API 0.3. Check that the source accepts the credential, without fetching items. Used for Connector Health."

    invocation_id: str
    contribution: Literal["connector"] = "connector"
    organization_id: str
    configuration: dict[str, Any]
    connector: ConnectorInstanceRef
    credential: Any
    now: str


@dataclass(kw_only=True)
class ConnectorCredentialResponse(Model):
    "200 body of POST /v0/contributions/connector/check_credential: the source accepts the credential. A refused credential is an error envelope with error_class access."

    status: Literal["ok"] = "ok"
    expires_at: str | None = None


@dataclass(kw_only=True)
class FixtureConnector(Model):
    kind: str
    config: dict[str, Any]


@dataclass(kw_only=True)
class ExpectedPage(Model):
    record_keys: list[str]
    more: bool | None = None


@dataclass(kw_only=True)
class ExpectedError(Model):
    "The first fetch is expected to fail with this error class."

    error_class: Literal["access", "transient", "source"]
    code: str | None = None


@dataclass(kw_only=True)
class ConnectorExpectationCheckCredential(Model):
    "The expected credential check: status ok, or an error_class (and optionally its code)."

    status: Literal["ok"] | None = None
    error_class: Literal["access", "transient", "source"] | None = None
    code: str | None = None


@dataclass(kw_only=True)
class ConnectorExpectation(Model):
    pages: list[ExpectedPage] | None = None
    error: ExpectedError | None = None
    check_credential: ConnectorExpectationCheckCredential | None = None


@dataclass(kw_only=True)
class FixtureReceiveRequest(Model):
    method: Literal["GET", "POST"]
    query: str | None = None
    headers: dict[str, str] | None = None
    body: str | None = None
    body_base64: str | None = None


@dataclass(kw_only=True)
class ExpectedDeliveryError(Model):
    "The delivery is expected to fail with this error class instead of a verdict."

    error_class: Literal["access", "transient", "source"]
    code: str | None = None


@dataclass(kw_only=True)
class ExpectedDelivery(Model):
    verdict: Literal["accepted", "refused"] | None = None
    status: int | None = None
    record_keys: list[str] | None = None
    body_contains: str | None = None
    error: ExpectedDeliveryError | None = None


@dataclass(kw_only=True)
class FixtureReceiveCase(Model):
    description: str | None = None
    request: FixtureReceiveRequest
    expect: ExpectedDelivery | None = None


@dataclass(kw_only=True)
class ConnectorFixture(Model):
    "A local test input that tools turn into connector requests: quivr plugin test fetches pages from checkpoint, feeding each returned checkpoint back, checks the credential and, for a push kind, relays each receive case. A file is a connector fixture when it has a top-level connector property. Fixture credentials are test values; the Contract Runner checks they never appear in responses or plugin logs."

    description: str | None = None
    connector: FixtureConnector
    credential: Any | None = None
    configuration: dict[str, Any] | None = None
    checkpoint: Any | None = None
    now: str | None = None
    max_pages: int | None = None
    expect: ConnectorExpectation | None = None
    receive: list[FixtureReceiveCase] | None = None


@dataclass(kw_only=True)
class AttachmentItem(Model):
    "The item the attachment belongs to, as the plugin returned it."

    record_key: str
    revision: str | None = None
    extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class ConnectorDescribeAttachmentRequest(Model):
    "POST /v0/contributions/connector/describe_attachment, since Plugin API 0.4. The core asks for the exact size and SHA-256 of one attachment of an item it has not accepted yet, before it issues an upload grant. The plugin reads the bytes from the source, at most attachments.max_bytes, or answers a skip."

    invocation_id: str
    contribution: Literal["connector"] = "connector"
    organization_id: str
    configuration: dict[str, Any]
    connector: ConnectorInstanceRef
    credential: Any
    now: str
    item: AttachmentItem
    attachment: ConnectorAttachment


@dataclass(kw_only=True)
class ConnectorDescribeAttachmentResponse(Model):
    "200 body of POST /v0/contributions/connector/describe_attachment: the exact size and SHA-256 of the bytes the plugin will upload, or a skip that leaves the attachment out of the item."

    size_bytes: int | None = None
    sha256: str | None = None
    skip: str | None = None
    item_extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class UploadAttachmentItem(Model):
    "The item the attachment belongs to, as the plugin returned it."

    record_key: str
    revision: str | None = None
    extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class UploadGrant(Model):
    "One presigned PUT for one storage object. Storage refuses any other length, checksum or media type. Send exactly these headers, never log the URL or the headers, and do not reuse the grant."

    url: str
    method: Literal["PUT"] = "PUT"
    headers: dict[str, str]
    size_bytes: int
    sha256: str
    media_type: str
    expires_at: str


@dataclass(kw_only=True)
class ConnectorUploadAttachmentRequest(Model):
    "POST /v0/contributions/connector/upload_attachment, since Plugin API 0.4. The plugin uploads the bytes it described to the grant, then answers. The core verifies the stored bytes before it accepts the item. Bytes that changed at the source since describe_attachment are a source error attachment_changed; the core describes the attachment again once."

    invocation_id: str
    contribution: Literal["connector"] = "connector"
    organization_id: str
    configuration: dict[str, Any]
    connector: ConnectorInstanceRef
    credential: Any
    now: str
    item: UploadAttachmentItem
    attachment: ConnectorAttachment
    grant: UploadGrant


@dataclass(kw_only=True)
class ConnectorUploadAttachmentResponse(Model):
    "200 body of POST /v0/contributions/connector/upload_attachment: the bytes were uploaded to the grant."

    status: Literal["uploaded"] = "uploaded"


@dataclass(kw_only=True)
class ReceiveInstanceRef(Model):
    "The Connector Instance the delivery is addressed to."

    instance_id: str
    kind: str
    corpus_id: str
    source_namespace: str
    config: dict[str, Any]


@dataclass(kw_only=True)
class RelayedRequest(Model):
    "The relayed request, bounded by the core: a body of at most 1 MiB, at most 64 header names. Hop-by-hop headers and Cookie are not relayed; declared API routes also remove Authorization."

    method: Literal["GET", "POST"]
    query: str
    headers: dict[str, list[str]]
    body_base64: str
    path: str | None = None


@dataclass(kw_only=True)
class ConnectorReceiveRequest(Model):
    "POST /v0/contributions/connector/receive for a push kind. Since Plugin API 0.5 the core relays public webhook requests for the plugin to verify and answer. Since 0.11 a declared API route adds route, parsed body and request.path after engine authorization. The core ingests accepted POST items and returns Receipts for declared routes; legacy webhooks and GET challenges keep the plugin answer."

    invocation_id: str
    contribution: Literal["connector"] = "connector"
    organization_id: str
    configuration: dict[str, Any]
    connector: ReceiveInstanceRef
    credential: Any
    checkpoint: Any
    now: str
    reads_today: int
    request: RelayedRequest
    route: str | None = None
    body: Any | None = None


@dataclass(kw_only=True)
class ReceiveAnswer(Model):
    "What the core answers the source: a 2xx status for accepted, a 4xx status for refused. A challenge (such as a CRC check) is an accepted delivery with no items whose body is the challenge answer."

    status: int
    content_type: str | None = None
    body: str | None = None


@dataclass(kw_only=True)
class ConnectorReceiveResponse(Model):
    "200 body of POST /v0/contributions/connector/receive: the plugin's verdict on one relayed delivery and the answer the core returns to the source. accepted: the delivery is authentic; the core ingests its items (the fetch item shape, without attachments) before answering, so an item a pull run also returns converges on the same Receipt. refused: the delivery is not authentic or not addressed to this instance; the core returns the answer and changes nothing. Since Plugin API 0.11, an accepted POST on a declared API route returns 202 with ingestion Receipts instead of the plugin response; GET challenges keep the plugin response and must carry no items."

    verdict: Literal["accepted", "refused"]
    response: ReceiveAnswer
    items: list[ConnectorItem] | None = None
    reads: int | None = None


@dataclass(kw_only=True)
class SegmentAndEmbedRequestVersion(Model):
    "The Record Version being ingested. Informational: the answer must depend only on the Parts, the language, the spaces and the configuration."

    corpus_id: str
    record_id: str
    record_version_id: str


@dataclass(kw_only=True)
class SegmentAndEmbedRequestPartsItem(Model):
    key: str
    role: str
    text: str


@dataclass(kw_only=True)
class SegmentAndEmbedRequest(Model):
    "POST /v0/contributions/ingestion/segment_and_embed, since Plugin API 0.6. One Record Version's text Parts and the enabled vector spaces to embed each segment in."

    invocation_id: str
    idempotency_key: str
    contribution: Literal["ingestion"] = "ingestion"
    organization_id: str
    configuration: dict[str, Any]
    version: SegmentAndEmbedRequestVersion
    language: str | None = None
    parts: list[SegmentAndEmbedRequestPartsItem]
    spaces: list[str]


@dataclass(kw_only=True)
class SegmentAndEmbedResponseSegmentsItem(Model):
    part_key: str
    start: int
    end: int
    vectors: dict[str, list[float]]
    lexical_text: str | None = None
    provenance: dict[str, Any] | None = None


@dataclass(kw_only=True)
class SegmentAndEmbedResponse(Model):
    "200 answer of segment_and_embed. Segments are listed in reading order; the core numbers them in that order."

    segments: list[SegmentAndEmbedResponseSegmentsItem]


@dataclass(kw_only=True)
class EmbedQueryRequestQuery(Model):
    modality: Literal["text"] = "text"
    text: str


@dataclass(kw_only=True)
class EmbedQueryRequest(Model):
    "POST /v0/contributions/ingestion/embed_query, since Plugin API 0.6. Encode one query into one of the plugin's spaces, so a query vector always comes from the model that produced the document vectors."

    invocation_id: str
    contribution: Literal["ingestion"] = "ingestion"
    organization_id: str
    configuration: dict[str, Any]
    space: str
    query: EmbedQueryRequestQuery


@dataclass(kw_only=True)
class EmbedQueryResponse(Model):
    "200 answer of embed_query."

    vector: list[float]


@dataclass(kw_only=True)
class IngestionFixtureIngestionExpectSegmentsItem(Model):
    part_key: str
    start: int
    end: int


@dataclass(kw_only=True)
class IngestionFixtureIngestionExpect(Model):
    segments: list[IngestionFixtureIngestionExpectSegmentsItem] | None = None
    lexical_text: bool | None = None


@dataclass(kw_only=True)
class IngestionFixtureIngestion(Model):
    parts: list[SegmentAndEmbedRequestPartsItem]
    language: str | None = None
    configuration: dict[str, Any] | None = None
    spaces: list[str] | None = None
    queries: list[str] | None = None
    expect: IngestionFixtureIngestionExpect | None = None


@dataclass(kw_only=True)
class IngestionFixture(Model):
    "A local test input for an ingestion plugin (since Plugin API 0.6): the text Parts of one Record Version, the queries to encode and what to expect. quivr plugin test turns it into segment_and_embed and embed_query requests."

    description: str | None = None
    ingestion: IngestionFixtureIngestion


@dataclass(kw_only=True)
class SearchRequestQuery(Model):
    text: str
    mode: Literal["lexical", "semantic", "hybrid"]


@dataclass(kw_only=True)
class SearchRequestScope(Model):
    corpus_ids: list[str]
    source_namespaces: list[str] | None = None


@dataclass(kw_only=True)
class SearchRequestSpacesItemOwner(Model):
    kind: Literal["engine", "plugin"]
    plugin_id: str | None = None
    plugin_version: str | None = None


@dataclass(kw_only=True)
class SearchRequestSpacesItemCoverage(Model):
    segments: int
    total: int


@dataclass(kw_only=True)
class SearchRequestSpacesItem(Model):
    "A vector space every requested Corpus's routed generation carries."

    id: str
    owner: SearchRequestSpacesItemOwner
    model: str
    dimensions: int
    metric: Literal["cosine", "dot", "l2"]
    indexes: list[str]
    query_modalities: list[str]
    role: Literal["served", "evaluation"]
    coverage: SearchRequestSpacesItemCoverage


@dataclass(kw_only=True)
class CandidateRequestFilter(Model):
    "Narrows the search's scope for this request; it never widens it."

    source_namespaces: list[str] | None = None


@dataclass(kw_only=True)
class CandidateRequest(Model):
    "One candidate request. bm25 ranks by keywords on a field; near_vector ranks by one space's vectors (the core encodes query_text with the space's owner, or takes vector as given); hybrid fuses both in one index query. Candidates are Record segments the caller may read, deduplicated by segment."

    primitive: Literal["bm25", "near_vector", "hybrid"]
    query_text: str | None = None
    vector: list[float] | None = None
    space: str | None = None
    field: Literal["source", "lexical"] | None = None
    alpha: float | None = None
    fusion: Literal["relative_score", "ranked"] | None = None
    k: int
    filter: CandidateRequestFilter | None = None
    group_by: Literal["record"] | None = None


@dataclass(kw_only=True)
class Candidate(Model):
    "One served candidate: an authorized, current segment of a Record."

    segment_id: str
    record_id: str
    version_id: str
    part_key: str
    text: str
    start: int
    end: int
    score: float


@dataclass(kw_only=True)
class SearchRequestServedItem(Model):
    round: int
    request_index: int
    request: CandidateRequest
    candidates: list[Candidate]


@dataclass(kw_only=True)
class SearchRequest(Model):
    "POST /v0/contributions/retrieval/search, since Plugin API 0.7. One round of one search: the query, the scope, the profile, the spaces available, and every candidate the core served in earlier rounds. The plugin answers candidate requests or the final ranking."

    invocation_id: str
    contribution: Literal["retrieval"] = "retrieval"
    organization_id: str
    configuration: dict[str, Any]
    profile: str
    round: int
    query: SearchRequestQuery
    limit: int
    scope: SearchRequestScope
    spaces: list[SearchRequestSpacesItem]
    served: list[SearchRequestServedItem]


@dataclass(kw_only=True)
class SearchResponseRankingHitsItem(Model):
    segment_id: str
    score: float
    explanation: str | None = None


@dataclass(kw_only=True)
class SearchResponseRanking(Model):
    hits: list[SearchResponseRankingHitsItem]


@dataclass(kw_only=True)
class SearchResponseUsage(Model):
    paid_calls: int | None = None
    cost_cents: float | None = None


@dataclass(kw_only=True)
class SearchResponse(Model):
    "The answer to one round: either candidate requests (the core serves them and calls the next round) or the final ranking, never both."

    requests: list[CandidateRequest] | None = None
    ranking: SearchResponseRanking | None = None
    usage: SearchResponseUsage | None = None


@dataclass(kw_only=True)
class RetrievalFixtureRetrievalCandidatesItem(Model):
    segment_id: str
    record_id: str
    source_namespace: str | None = None
    text: str


@dataclass(kw_only=True)
class RetrievalFixtureRetrievalOrder(Model):
    "The exact segment order a primitive serves, whatever its query."

    bm25: list[str] | None = None
    near_vector: list[str] | None = None
    hybrid: list[str] | None = None


@dataclass(kw_only=True)
class RetrievalFixtureRetrievalExpect(Model):
    top: list[str] | None = None


@dataclass(kw_only=True)
class RetrievalFixtureRetrieval(Model):
    query: str
    mode: Literal["lexical", "semantic", "hybrid"] | None = None
    limit: int | None = None
    configuration: dict[str, Any] | None = None
    profiles: list[str] | None = None
    spaces: list[str] | None = None
    candidates: list[RetrievalFixtureRetrievalCandidatesItem]
    order: RetrievalFixtureRetrievalOrder | None = None
    expect: RetrievalFixtureRetrievalExpect | None = None


@dataclass(kw_only=True)
class RetrievalFixture(Model):
    "A local test input for a retrieval plugin (since Plugin API 0.7): a query, the spaces available and a catalogue of candidates. quivr plugin test drives the rounds and serves candidates from the catalogue, offline."

    description: str | None = None
    retrieval: RetrievalFixtureRetrieval


# Keys are extension namespaces.
Extensions = dict[str, ExtensionEntry]

__all__ = [
    "AttachmentItem",
    "BlobContent",
    "Candidate",
    "CandidateRequest",
    "CandidateRequestFilter",
    "ConnectorAPI",
    "ConnectorAPIRoute",
    "ConnectorAttachment",
    "ConnectorContribution",
    "ConnectorContributionAttachments",
    "ConnectorCredentialRequest",
    "ConnectorCredentialResponse",
    "ConnectorDescribeAttachmentRequest",
    "ConnectorDescribeAttachmentResponse",
    "ConnectorExpectation",
    "ConnectorExpectationCheckCredential",
    "ConnectorFetchRequest",
    "ConnectorFetchResponse",
    "ConnectorFixture",
    "ConnectorInstanceRef",
    "ConnectorItem",
    "ConnectorKind",
    "ConnectorLimits",
    "ConnectorOrigin",
    "ConnectorReceiveRequest",
    "ConnectorReceiveResponse",
    "ConnectorUploadAttachmentRequest",
    "ConnectorUploadAttachmentResponse",
    "Decision",
    "Discovery",
    "EmbedQueryRequest",
    "EmbedQueryRequestQuery",
    "EmbedQueryResponse",
    "ErrorEnvelope",
    "EvaluatedRecord",
    "Evaluation",
    "EvaluationQueryVector",
    "Evidence",
    "ExpectedDelivery",
    "ExpectedDeliveryError",
    "ExpectedError",
    "ExpectedPage",
    "ExtensionEntry",
    "Extensions",
    "FileReference",
    "FixtureConnector",
    "FixtureEvaluation",
    "FixtureInput",
    "FixtureReceiveCase",
    "FixtureReceiveRequest",
    "FixtureRecord",
    "Health",
    "Ingestion",
    "IngestionFixture",
    "IngestionFixtureIngestion",
    "IngestionFixtureIngestionExpect",
    "IngestionFixtureIngestionExpectSegmentsItem",
    "IngestionLimits",
    "InputBlob",
    "InvocationFixture",
    "ManifestCompatibility",
    "ManifestConfiguration",
    "ManifestContent",
    "ManifestContributions",
    "NormalizationOrigin",
    "NormalizationProvenance",
    "NormalizationProvenanceFallback",
    "NormalizerContribution",
    "NormalizerRequest",
    "NormalizerResponse",
    "OutputLimits",
    "Part",
    "PluginIdentity",
    "PluginManifest",
    "Provenance",
    "PushStatus",
    "ReceiveAnswer",
    "ReceiveInstanceRef",
    "RecordPart",
    "RecordPartVectorsItem",
    "RecordProvenance",
    "RecordSource",
    "RelationInput",
    "RelayedRequest",
    "ResponseWarning",
    "Retrieval",
    "RetrievalFixture",
    "RetrievalFixtureRetrieval",
    "RetrievalFixtureRetrievalCandidatesItem",
    "RetrievalFixtureRetrievalExpect",
    "RetrievalFixtureRetrievalOrder",
    "RetrievalLimits",
    "RetrievalProfile",
    "RetryIntent",
    "RunCommand",
    "SearchRequest",
    "SearchRequestQuery",
    "SearchRequestScope",
    "SearchRequestServedItem",
    "SearchRequestSpacesItem",
    "SearchRequestSpacesItemCoverage",
    "SearchRequestSpacesItemOwner",
    "SearchResponse",
    "SearchResponseRanking",
    "SearchResponseRankingHitsItem",
    "SearchResponseUsage",
    "Secret",
    "SegmentAndEmbedRequest",
    "SegmentAndEmbedRequestPartsItem",
    "SegmentAndEmbedRequestVersion",
    "SegmentAndEmbedResponse",
    "SegmentAndEmbedResponseSegmentsItem",
    "SignedUrlReference",
    "SourceIdentity",
    "SubscriptionContribution",
    "SubscriptionContributionVectors",
    "SubscriptionFixture",
    "SubscriptionLimits",
    "SubscriptionRef",
    "SubscriptionRequest",
    "SubscriptionResponse",
    "TextContent",
    "UploadAttachmentItem",
    "UploadGrant",
    "VectorSpace",
    "VectorSpaceInputPrice",
]
