"""Typed Plugin Protocol v0 models.

Code generated by sdks/python/scripts/generate.py from contracts/shared/v0 and
contracts/plugins/v0. DO NOT EDIT.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

from ._codec import Model


@dataclass(kw_only=True)
class SourceIdentity(Model):
    corpus_id: str
    namespace: str
    record_key: str


@dataclass(kw_only=True)
class ExtensionEntry(Model):
    schema_version: str
    data: dict[str, Any]


@dataclass(kw_only=True)
class TextContent(Model):
    kind: Literal["text"] = "text"
    text: str


@dataclass(kw_only=True)
class BlobContent(Model):
    kind: Literal["blob"] = "blob"
    blob_id: str
    media_type: str


@dataclass(kw_only=True)
class Part(Model):
    key: str
    parent_key: str | None = None
    role: str
    content: TextContent | BlobContent
    extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class RelationInput(Model):
    "Source-provided link to an independently identified Record in the same Organization. Optional source revision preserves provenance; ordinary expansion resolves the current eligible target. Missing targets do not block readiness. Every expansion reauthorizes the target. Precise Part-target syntax remains outside this initial draft."

    type: str
    target: SourceIdentity
    source_target_revision: str | None = None


@dataclass(kw_only=True)
class ManifestContent(Model):
    "Unique Part keys, acyclic parent references within this Manifest, and verified same-Organization Blobs are checked before atomic publication. These semantic constraints need server validation in addition to JSON Schema."

    kind: Literal["manifest"] = "manifest"
    parts: list[Part]
    relations: list[RelationInput] | None = None


@dataclass(kw_only=True)
class NormalizationProvenanceFallback(Model):
    "Present when the route is optional and the normalizer failed: the published Manifest comes from the built-in text path, and invocation_id names the failed invocation."

    code: str
    message: str


@dataclass(kw_only=True)
class NormalizationProvenance(Model):
    "Engine-owned record of the external normalizer invocation whose output a Record Version publishes. Present only on read; a submission that sets it is rejected. producer and producer_version keep naming the acquirer, and source_blob_ids keeps the input Blob."

    plugin_id: str
    plugin_version: str
    plugin_api: str
    contribution: Literal["normalizer"] = "normalizer"
    invocation_id: str
    idempotency_key: str
    input_sha256: str
    fallback: NormalizationProvenanceFallback | None = None


@dataclass(kw_only=True)
class Provenance(Model):
    source_blob_ids: list[str] | None = None
    producer: str | None = None
    producer_version: str | None = None
    normalization: NormalizationProvenance | None = None


@dataclass(kw_only=True)
class SignedUrlReference(Model):
    "Short-lived signed GET URL for the input Blob."

    kind: Literal["signed_url"] = "signed_url"
    url: str
    expires_at: str


@dataclass(kw_only=True)
class FileReference(Model):
    "Local development only: a file URL readable by the plugin."

    kind: Literal["file"] = "file"
    url: str


@dataclass(kw_only=True)
class InputBlob(Model):
    blob_id: str
    media_type: str
    size_bytes: int
    sha256: str
    reference: SignedUrlReference | FileReference


@dataclass(kw_only=True)
class NormalizerRequest(Model):
    "POST /v0/contributions/normalizer. Immutable invocation context plus a reference to the input Blob; bodies are never inline."

    invocation_id: str
    idempotency_key: str
    contribution: Literal["normalizer"] = "normalizer"
    organization_id: str
    corpus_id: str
    record_id: str
    record_version_id: str
    source: SourceIdentity
    input: InputBlob
    extensions: dict[str, ExtensionEntry] | None = None
    provenance: Provenance | None = None
    configuration: dict[str, Any]


@dataclass(kw_only=True)
class ResponseWarning(Model):
    code: str
    message: str


@dataclass(kw_only=True)
class NormalizerResponse(Model):
    "200 body of POST /v0/contributions/normalizer. The Manifest uses the exact public Manifest shape; the engine applies the same semantic validation as for kind manifest submissions before anything is committed."

    manifest: ManifestContent
    extensions: dict[str, ExtensionEntry] | None = None
    language: str | None = None
    warnings: list[ResponseWarning] | None = None


@dataclass(kw_only=True)
class PluginIdentity(Model):
    id: str
    version: str


@dataclass(kw_only=True)
class Discovery(Model):
    "GET /v0/discovery. manifest_digest is sha256 over the exact bytes of the quivr-plugin.yaml the plugin was built from; the engine compares it with the pinned manifest."

    plugin_api: str
    plugin: PluginIdentity
    manifest_digest: str
    contributions: list[Literal["normalizer", "subscription"]]


@dataclass(kw_only=True)
class Health(Model):
    "GET /v0/health returns 200 with this body when the plugin can accept invocations; otherwise 503 with the error envelope."

    status: Literal["ok"] = "ok"


@dataclass(kw_only=True)
class ErrorEnvelope(Model):
    "Body of every non-2xx plugin response. retryable is authoritative: true asks the engine to retry within the declared retry intent; false is terminal."

    code: str
    message: str
    retryable: bool


@dataclass(kw_only=True)
class ManifestCompatibility(Model):
    engine: str
    plugin_api: str


@dataclass(kw_only=True)
class RetryIntent(Model):
    "Retry intent for plugin-declared retryable errors; the engine may cap it."

    max_attempts: int


@dataclass(kw_only=True)
class OutputLimits(Model):
    max_response_bytes: int | None = None
    max_parts: int | None = None


@dataclass(kw_only=True)
class NormalizerContribution(Model):
    media_types: list[str]
    timeout_ms: int | None = None
    retry: RetryIntent | None = None
    limits: OutputLimits | None = None


@dataclass(kw_only=True)
class SubscriptionLimits(Model):
    max_response_bytes: int | None = None


@dataclass(kw_only=True)
class SubscriptionContribution(Model):
    "An alert rule, since Plugin API 0.2: decides whether one Record Version matches each Saved Query expression of a batch."

    expression_schema: Any
    configuration_schema: Any | None = None
    max_batch_size: int | None = None
    timeout_ms: int | None = None
    retry: RetryIntent | None = None
    limits: SubscriptionLimits | None = None


@dataclass(kw_only=True)
class ManifestContributions(Model):
    "Keyed by Contribution name. A manifest declares at least one of normalizer (since Plugin API 0.1) and subscription (since 0.2). The other names are reserved and rejected."

    normalizer: NormalizerContribution | None = None
    subscription: SubscriptionContribution | None = None


@dataclass(kw_only=True)
class ManifestConfiguration(Model):
    schema: Any


@dataclass(kw_only=True)
class Secret(Model):
    name: str
    description: str | None = None
    required: bool | None = None


@dataclass(kw_only=True)
class RunCommand(Model):
    "Language-neutral local development command (argv, no shell)."

    command: list[str]


@dataclass(kw_only=True)
class PluginManifest(Model):
    "Declares one plugin: identity, compatibility ranges, Contributions, configuration schema, required secrets, owned extension namespaces and a local run command. Written as YAML; validated as the equivalent JSON value. Semantic rules this schema cannot express (satisfiable ranges, compatibility, namespace prefix, schemas that compile) are listed in README.md."

    id: str
    version: str
    description: str | None = None
    compatibility: ManifestCompatibility
    contributions: ManifestContributions
    configuration: ManifestConfiguration | None = None
    secrets: list[Secret] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    run: RunCommand | None = None


@dataclass(kw_only=True)
class FixtureInput(Model):
    path: str
    media_type: str


@dataclass(kw_only=True)
class InvocationFixture(Model):
    "A language-neutral local test input for a normalizer. Tools (quivr plugin dev, the Contract Runner, SDK test helpers) turn it into a normalizer request: they read input.path relative to the fixture file, compute its size and SHA-256, reference it through an absolute file:// URL, and fill the identity fields with deterministic development values."

    description: str | None = None
    input: FixtureInput
    configuration: dict[str, Any] | None = None
    source: SourceIdentity | None = None
    extensions: dict[str, ExtensionEntry] | None = None
    provenance: Provenance | None = None


@dataclass(kw_only=True)
class RecordPart(Model):
    key: str
    role: str
    text: str


@dataclass(kw_only=True)
class RecordSource(Model):
    "Where the Record comes from: its Source Namespace and Record Key, and the Source Position of the accepted revision when the producer sent one. Always sent by the core since Plugin API 0.2."

    namespace: str
    record_key: str
    position: str | None = None


@dataclass(kw_only=True)
class ConnectorOrigin(Model):
    "Present when origin is connector."

    instance_id: str
    kind: str


@dataclass(kw_only=True)
class NormalizationOrigin(Model):
    "Present when an external normalizer produced the published Manifest."

    plugin_id: str
    plugin_version: str
    contribution: Literal["normalizer"] = "normalizer"
    fallback: bool | None = None


@dataclass(kw_only=True)
class RecordProvenance(Model):
    "Who produced the Version. Always sent by the core since Plugin API 0.2."

    origin: Literal["client", "connector"]
    producer: str | None = None
    producer_version: str | None = None
    connector: ConnectorOrigin | None = None
    normalization: NormalizationOrigin | None = None


@dataclass(kw_only=True)
class EvaluatedRecord(Model):
    "The evaluated Record Version."

    corpus_id: str
    record_id: str
    record_version_id: str
    enriched: bool
    parts: list[RecordPart]
    source: RecordSource | None = None
    accepted_at: str | None = None
    provenance: RecordProvenance | None = None
    extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class SubscriptionRef(Model):
    subscription_id: str
    subscription_version_id: str
    saved_query_id: str
    saved_query_version_id: str
    owner: str | None = None


@dataclass(kw_only=True)
class Evaluation(Model):
    id: str
    expression: dict[str, Any]
    configuration: dict[str, Any]
    subscriptions: list[SubscriptionRef]


@dataclass(kw_only=True)
class SubscriptionRequest(Model):
    "POST /v0/contributions/subscription, since Plugin API 0.2. One Record Version's text Parts and metadata (source identity, acceptance time, provenance, extensions) and a batch of distinct evaluations to decide. The core deduplicates Subscriptions that share the same expression and configuration into one evaluation and never sends more evaluations than the manifest's max_batch_size."

    invocation_id: str
    idempotency_key: str
    contribution: Literal["subscription"] = "subscription"
    organization_id: str
    record: EvaluatedRecord
    evaluations: list[Evaluation]
    configuration: dict[str, Any]


@dataclass(kw_only=True)
class Evidence(Model):
    "Required for match, optional otherwise."

    explanation: str
    part_keys: list[str] | None = None
    details: dict[str, Any] | None = None


@dataclass(kw_only=True)
class Decision(Model):
    id: str
    decision: Literal["match", "no_match", "not_ready"]
    evidence: Evidence | None = None


@dataclass(kw_only=True)
class SubscriptionResponse(Model):
    "200 body of POST /v0/contributions/subscription, since Plugin API 0.2. Exactly one decision per requested evaluation id. A match carries evidence; the core stores it with the Match. Bounds this schema cannot express (one decision per id, Part keys that exist in the request, details of at most 16 KiB) are listed in README.md."

    decisions: list[Decision]


@dataclass(kw_only=True)
class FixtureRecord(Model):
    enriched: bool | None = None
    parts: list[RecordPart]
    source: RecordSource | None = None
    accepted_at: str | None = None
    provenance: RecordProvenance | None = None
    extensions: dict[str, ExtensionEntry] | None = None


@dataclass(kw_only=True)
class FixtureEvaluation(Model):
    description: str | None = None
    expression: dict[str, Any]
    configuration: dict[str, Any] | None = None
    expect: Literal["match", "no_match", "not_ready"] | None = None


@dataclass(kw_only=True)
class SubscriptionFixture(Model):
    "A language-neutral local test input for a subscription Contribution, since Plugin API 0.2. Tools (quivr plugin dev, the Contract Runner, SDK test helpers) turn it into a subscription request: they number the evaluations e1, e2, ... in order, give each one development Subscription ids, derive the Record Version ids and the idempotency key from the SHA-256 of the fixture bytes, default the record metadata (source dev-namespace/dev-record-<digest>, origin client, accepted_at 2026-01-01T00:00:00Z) when the fixture omits it, and validate every expression and configuration against the manifest schemas. A fixture file is told apart from an invocation fixture by its top-level evaluations property."

    description: str | None = None
    configuration: dict[str, Any] | None = None
    record: FixtureRecord
    evaluations: list[FixtureEvaluation]


# Keys are extension namespaces.
Extensions = dict[str, ExtensionEntry]

__all__ = [
    "BlobContent",
    "ConnectorOrigin",
    "Decision",
    "Discovery",
    "ErrorEnvelope",
    "EvaluatedRecord",
    "Evaluation",
    "Evidence",
    "ExtensionEntry",
    "Extensions",
    "FileReference",
    "FixtureEvaluation",
    "FixtureInput",
    "FixtureRecord",
    "Health",
    "InputBlob",
    "InvocationFixture",
    "ManifestCompatibility",
    "ManifestConfiguration",
    "ManifestContent",
    "ManifestContributions",
    "NormalizationOrigin",
    "NormalizationProvenance",
    "NormalizationProvenanceFallback",
    "NormalizerContribution",
    "NormalizerRequest",
    "NormalizerResponse",
    "OutputLimits",
    "Part",
    "PluginIdentity",
    "PluginManifest",
    "Provenance",
    "RecordPart",
    "RecordProvenance",
    "RecordSource",
    "RelationInput",
    "ResponseWarning",
    "RetryIntent",
    "RunCommand",
    "Secret",
    "SignedUrlReference",
    "SourceIdentity",
    "SubscriptionContribution",
    "SubscriptionFixture",
    "SubscriptionLimits",
    "SubscriptionRef",
    "SubscriptionRequest",
    "SubscriptionResponse",
    "TextContent",
]
