# Generated by deploy/infrastructure.py generate; edit deploy/infrastructure.json.
FROM golang:1.27.2-bookworm@sha256:5cf287a799e6b94384bad13d16b14904c531f51ba65792237e122ce42b392f61 AS build
WORKDIR /app
COPY go.mod go.sum ./
COPY cmd/quivr-index-warmup ./cmd/quivr-index-warmup
COPY internal/indexwarmup ./internal/indexwarmup
RUN CGO_ENABLED=0 go build -trimpath -o /quivr-index-warmup ./cmd/quivr-index-warmup

FROM debian:bookworm-slim@sha256:7c7b2c966bc9ee8cedfeef67e0e279108992c77681fa595db4a9d65c06ccc587
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
USER 65532:65532
COPY --from=build /quivr-index-warmup /usr/local/bin/quivr-index-warmup
ENTRYPOINT ["/usr/local/bin/quivr-index-warmup"]
